"""baseline schema

Revision ID: 03bcf150bdbf
Revises: 
Create Date: 2026-07-23 23:07:04.935308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03bcf150bdbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('diff_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('dataset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('includes_imputed', sa.Boolean(), nullable=True),
    sa.Column('only_approved', sa.Boolean(), nullable=True),
    sa.Column('feature_config_json', sa.Text(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_snapshots_id'), 'dataset_snapshots', ['id'], unique=False)
    op.create_table('ext_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=False),
    sa.Column('indicator_unit', sa.String(), nullable=False),
    sa.Column('indicator_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'indicator_type', 'indicator_unit', name='uq_ext_ind_proj_type_unit')
    )
    op.create_index(op.f('ix_ext_indicators_id'), 'ext_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_ext_indicators_project_id'), 'ext_indicators', ['project_id'], unique=False)
    op.create_table('ext_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('functional_class', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ingredient_name', name='uq_ext_ing_proj_name')
    )
    op.create_index(op.f('ix_ext_ingredients_id'), 'ext_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ext_ingredients_project_id'), 'ext_ingredients', ['project_id'], unique=False)
    op.create_table('microorganisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('genus', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('strain', sa.String(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('organism_role', sa.String(), nullable=True),
    sa.Column('gram_category', sa.String(), nullable=True),
    sa.Column('synonyms_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microorganisms_id'), 'microorganisms', ['id'], unique=False)
    op.create_table('normalization_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('original_term', sa.String(), nullable=False),
    sa.Column('canonical_term', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('applied_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'mapping_type', 'original_term', name='uq_norm_mapping')
    )
    op.create_index(op.f('ix_normalization_mappings_id'), 'normalization_mappings', ['id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_file_hash'), 'papers', ['file_hash'], unique=False)
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_member')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('threshold_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('threshold_unit', sa.String(), nullable=True),
    sa.Column('comparison_operator', sa.String(), nullable=True),
    sa.Column('product_scope', sa.String(), nullable=True),
    sa.Column('microorganism_scope', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threshold_definitions_id'), 'threshold_definitions', ['id'], unique=False)
    op.create_table('uploaded_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('dataset_family', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('column_types_json', sa.Text(), nullable=True),
    sa.Column('column_mapping_json', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_datasets_file_hash'), 'uploaded_datasets', ['file_hash'], unique=False)
    op.create_index(op.f('ix_uploaded_datasets_id'), 'uploaded_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_datasets_project_id'), 'uploaded_datasets', ['project_id'], unique=False)
    op.create_table('docling_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('cache_dir', sa.String(), nullable=False),
    sa.Column('markdown_path', sa.String(), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('figure_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('docling_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docling_cache_file_hash'), 'docling_cache', ['file_hash'], unique=True)
    op.create_index(op.f('ix_docling_cache_id'), 'docling_cache', ['id'], unique=False)
    op.create_index(op.f('ix_docling_cache_paper_id'), 'docling_cache', ['paper_id'], unique=False)
    op.create_table('export_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_runs_id'), 'export_runs', ['id'], unique=False)
    op.create_table('ext_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_key', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=True),
    sa.Column('exact_text', sa.Text(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('figure_series', sa.String(), nullable=True),
    sa.Column('x_axis_value', sa.Float(), nullable=True),
    sa.Column('y_axis_value', sa.Float(), nullable=True),
    sa.Column('value_is_approximate', sa.Boolean(), nullable=True),
    sa.Column('evidence_image_path', sa.String(), nullable=True),
    sa.Column('evidence_thumbnail_path', sa.String(), nullable=True),
    sa.Column('docling_item_ref', sa.String(), nullable=True),
    sa.Column('is_chart_derived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_evidence_id'), 'ext_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_ext_evidence_paper_id'), 'ext_evidence', ['paper_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors_json', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('doi_original', sa.String(), nullable=True),
    sa.Column('doi_normalized', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('study_type', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('legacy_row_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legacy_row_id'], ['extracted_rows.id'], name='fk_studies_legacy_row_id', use_alter=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_doi_normalized'), 'studies', ['doi_normalized'], unique=False)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index('ix_study_project_doi', 'studies', ['project_id', 'doi_normalized'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('experiment_label', sa.String(), nullable=True),
    sa.Column('food_category', sa.String(), nullable=True),
    sa.Column('product_name_original', sa.String(), nullable=True),
    sa.Column('product_name_normalized', sa.String(), nullable=True),
    sa.Column('product_family', sa.String(), nullable=True),
    sa.Column('matrix_description', sa.Text(), nullable=True),
    sa.Column('milk_species', sa.String(), nullable=True),
    sa.Column('milk_treatment', sa.String(), nullable=True),
    sa.Column('fat_content_class', sa.String(), nullable=True),
    sa.Column('sampling_location', sa.String(), nullable=True),
    sa.Column('storage_temperature_value', sa.Float(), nullable=True),
    sa.Column('storage_temperature_unit_original', sa.String(), nullable=True),
    sa.Column('storage_temperature_c', sa.Float(), nullable=True),
    sa.Column('storage_relative_humidity', sa.Float(), nullable=True),
    sa.Column('packaging_type', sa.String(), nullable=True),
    sa.Column('atmosphere_type', sa.String(), nullable=True),
    sa.Column('gas_composition_json', sa.Text(), nullable=True),
    sa.Column('light_condition', sa.String(), nullable=True),
    sa.Column('storage_duration_value', sa.Float(), nullable=True),
    sa.Column('storage_duration_unit_original', sa.String(), nullable=True),
    sa.Column('storage_duration_days', sa.Float(), nullable=True),
    sa.Column('study_design', sa.String(), nullable=True),
    sa.Column('replicate_design', sa.String(), nullable=True),
    sa.Column('artificial_inoculation', sa.Boolean(), nullable=True),
    sa.Column('initial_ph', sa.Float(), nullable=True),
    sa.Column('initial_water_activity', sa.Float(), nullable=True),
    sa.Column('initial_salt_pct', sa.Float(), nullable=True),
    sa.Column('initial_moisture_pct', sa.Float(), nullable=True),
    sa.Column('extra_conditions_json', sa.Text(), nullable=True),
    sa.Column('condition_signature', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_condition_signature'), 'experiments', ['condition_signature'], unique=False)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('ext_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('meat_matrix', sa.String(), nullable=False),
    sa.Column('treatment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_experiments_id'), 'ext_experiments', ['id'], unique=False)
    op.create_index(op.f('ix_ext_experiments_paper_id'), 'ext_experiments', ['paper_id'], unique=False)
    op.create_index(op.f('ix_ext_experiments_project_id'), 'ext_experiments', ['project_id'], unique=False)
    op.create_table('extracted_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('canonical_study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_rows_id'), 'extracted_rows', ['id'], unique=False)
    op.create_table('extraction_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('docling_item_ref', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('page_image_path', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('conversion_status', sa.String(), nullable=True),
    sa.Column('conversion_error', sa.String(), nullable=True),
    sa.Column('csv_rows', sa.Integer(), nullable=True),
    sa.Column('csv_cols', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('selected_for_llm', sa.Boolean(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_assets_id'), 'extraction_assets', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_assets_paper_id'), 'extraction_assets', ['paper_id'], unique=False)
    op.create_index(op.f('ix_extraction_assets_project_id'), 'extraction_assets', ['project_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=True),
    sa.Column('chunks_created', sa.Integer(), nullable=True),
    sa.Column('rows_extracted', sa.Integer(), nullable=True),
    sa.Column('tables_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_id'), 'extraction_runs', ['id'], unique=False)
    op.create_table('figure_conversion_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docling_cache_id', sa.Integer(), nullable=False),
    sa.Column('figure_index', sa.Integer(), nullable=False),
    sa.Column('item_ref', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docling_cache_id'], ['docling_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figure_conversion_cache_docling_cache_id'), 'figure_conversion_cache', ['docling_cache_id'], unique=False)
    op.create_index(op.f('ix_figure_conversion_cache_id'), 'figure_conversion_cache', ['id'], unique=False)
    op.create_table('lab_training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('dataset_family', sa.String(), nullable=False),
    sa.Column('column_mapping_json', sa.Text(), nullable=True),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('n_trajectories', sa.Integer(), nullable=True),
    sa.Column('n_fitted', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['uploaded_datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_training_runs_id'), 'lab_training_runs', ['id'], unique=False)
    op.create_index(op.f('ix_lab_training_runs_job_id'), 'lab_training_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_lab_training_runs_project_id'), 'lab_training_runs', ['project_id'], unique=False)
    op.create_table('asset_context_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('item_ref', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['extraction_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_context_links_asset_id'), 'asset_context_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_context_links_id'), 'asset_context_links', ['id'], unique=False)
    op.create_table('experiment_microorganisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('microorganism_id', sa.Integer(), nullable=False),
    sa.Column('role_in_study', sa.String(), nullable=True),
    sa.Column('inoculum_level', sa.Float(), nullable=True),
    sa.Column('inoculum_unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['microorganism_id'], ['microorganisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'microorganism_id', name='uq_exp_micro')
    )
    op.create_index(op.f('ix_experiment_microorganisms_id'), 'experiment_microorganisms', ['id'], unique=False)
    op.create_table('ext_experiment_ingredients',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('concentration_unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ext_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ext_ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id', 'ingredient_id')
    )
    op.create_table('ext_measurements',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('indicator_value', sa.Float(), nullable=False),
    sa.Column('value_is_approximate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['ext_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['ext_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id', 'day', 'indicator_id')
    )
    op.create_table('lab_model_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_run_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_family', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('preprocessing_path', sa.String(), nullable=True),
    sa.Column('feature_cols_json', sa.Text(), nullable=True),
    sa.Column('target_col', sa.String(), nullable=True),
    sa.Column('event_col', sa.String(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('concordance_index', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['training_run_id'], ['lab_training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_model_results_id'), 'lab_model_results', ['id'], unique=False)
    op.create_index(op.f('ix_lab_model_results_project_id'), 'lab_model_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_lab_model_results_training_run_id'), 'lab_model_results', ['training_run_id'], unique=False)
    op.create_table('treatment_arms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('arm_label', sa.String(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=True),
    sa.Column('control_arm_id', sa.Integer(), nullable=True),
    sa.Column('treatment_type', sa.String(), nullable=True),
    sa.Column('ingredient_name_original', sa.String(), nullable=True),
    sa.Column('ingredient_name_normalized', sa.String(), nullable=True),
    sa.Column('ingredient_source', sa.String(), nullable=True),
    sa.Column('ingredient_family', sa.String(), nullable=True),
    sa.Column('concentration_value_original', sa.Float(), nullable=True),
    sa.Column('concentration_unit_original', sa.String(), nullable=True),
    sa.Column('concentration_value_normalized', sa.Float(), nullable=True),
    sa.Column('concentration_unit_normalized', sa.String(), nullable=True),
    sa.Column('application_method', sa.String(), nullable=True),
    sa.Column('treatment_timing', sa.String(), nullable=True),
    sa.Column('combination_treatments_json', sa.Text(), nullable=True),
    sa.Column('extra_treatment_json', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_arm_id'], ['treatment_arms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_arms_id'), 'treatment_arms', ['id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_arm_id', sa.Integer(), nullable=False),
    sa.Column('microorganism_id', sa.Integer(), nullable=True),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('measurement_subtype', sa.String(), nullable=True),
    sa.Column('measurement_unit_normalized', sa.String(), nullable=True),
    sa.Column('time_value_original', sa.Float(), nullable=True),
    sa.Column('time_unit_original', sa.String(), nullable=True),
    sa.Column('time_days', sa.Float(), nullable=True),
    sa.Column('value_original_text', sa.String(), nullable=True),
    sa.Column('numeric_value_original', sa.Float(), nullable=True),
    sa.Column('unit_original', sa.String(), nullable=True),
    sa.Column('numeric_value_normalized', sa.Float(), nullable=True),
    sa.Column('unit_normalized', sa.String(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('standard_error', sa.Float(), nullable=True),
    sa.Column('minimum_value', sa.Float(), nullable=True),
    sa.Column('maximum_value', sa.Float(), nullable=True),
    sa.Column('replicate_count', sa.Integer(), nullable=True),
    sa.Column('detection_limit', sa.Float(), nullable=True),
    sa.Column('detection_limit_unit', sa.String(), nullable=True),
    sa.Column('censoring_type', sa.String(), nullable=True),
    sa.Column('value_origin', sa.String(), nullable=True),
    sa.Column('missing_reason', sa.String(), nullable=True),
    sa.Column('is_imputed', sa.Boolean(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=True),
    sa.Column('significance_letter', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('extraction_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['microorganism_id'], ['microorganisms.id'], ),
    sa.ForeignKeyConstraint(['treatment_arm_id'], ['treatment_arms.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_arm_time', 'observations', ['treatment_arm_id', 'time_days'], unique=False)
    op.create_index('ix_obs_type', 'observations', ['measurement_type'], unique=False)
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_table('trajectory_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('treatment_arm_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('measurement_subtype', sa.String(), nullable=True),
    sa.Column('microorganism_id', sa.Integer(), nullable=True),
    sa.Column('process_class', sa.String(), nullable=True),
    sa.Column('grouping_signature', sa.String(), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=True),
    sa.Column('time_min_days', sa.Float(), nullable=True),
    sa.Column('time_max_days', sa.Float(), nullable=True),
    sa.Column('has_control', sa.Boolean(), nullable=True),
    sa.Column('data_sufficient', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['microorganism_id'], ['microorganisms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['treatment_arm_id'], ['treatment_arms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_definitions_grouping_signature'), 'trajectory_definitions', ['grouping_signature'], unique=False)
    op.create_index(op.f('ix_trajectory_definitions_id'), 'trajectory_definitions', ['id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('models_tried', sa.Integer(), nullable=True),
    sa.Column('models_converged', sa.Integer(), nullable=True),
    sa.Column('selected_model_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selected_model_id'], ['model_fits.id'], name='fk_model_runs_selected_model_id', use_alter=True),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_id'), 'model_runs', ['id'], unique=False)
    op.create_table('trajectory_observations',
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trajectory_id', 'observation_id')
    )
    op.create_table('model_fits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('process_class', sa.String(), nullable=True),
    sa.Column('converged', sa.Boolean(), nullable=True),
    sa.Column('convergence_message', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('parameter_bounds_json', sa.Text(), nullable=True),
    sa.Column('parameter_se_json', sa.Text(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('adjusted_r_squared', sa.Float(), nullable=True),
    sa.Column('aic', sa.Float(), nullable=True),
    sa.Column('bic', sa.Float(), nullable=True),
    sa.Column('aicc', sa.Float(), nullable=True),
    sa.Column('residual_bias', sa.Float(), nullable=True),
    sa.Column('loo_mae', sa.Float(), nullable=True),
    sa.Column('loo_rmse', sa.Float(), nullable=True),
    sa.Column('biological_violations', sa.Integer(), nullable=True),
    sa.Column('applicability_status', sa.String(), nullable=True),
    sa.Column('applicability_reasons_json', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('equation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_fits_id'), 'model_fits', ['id'], unique=False)
    op.create_table('imputation_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=True),
    sa.Column('fit_id', sa.Integer(), nullable=True),
    sa.Column('target_observation_id', sa.Integer(), nullable=True),
    sa.Column('target_arm_id', sa.Integer(), nullable=True),
    sa.Column('target_time_days', sa.Float(), nullable=True),
    sa.Column('target_measurement_type', sa.String(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('interval_type', sa.String(), nullable=True),
    sa.Column('is_interpolation', sa.Boolean(), nullable=True),
    sa.Column('extrapolation_days', sa.Float(), nullable=True),
    sa.Column('applicability_status', sa.String(), nullable=True),
    sa.Column('applicability_reasons_json', sa.Text(), nullable=True),
    sa.Column('cross_validation_mae', sa.Float(), nullable=True),
    sa.Column('cross_validation_rmse', sa.Float(), nullable=True),
    sa.Column('n_points_used', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('reviewer_decision', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fit_id'], ['model_fits.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_arm_id'], ['treatment_arms.id'], ),
    sa.ForeignKeyConstraint(['target_observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imputation_proposals_id'), 'imputation_proposals', ['id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_id', sa.Integer(), nullable=False),
    sa.Column('time_days', sa.Float(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('interval_type', sa.String(), nullable=True),
    sa.Column('interval_level', sa.Float(), nullable=True),
    sa.Column('is_interpolation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fit_id'], ['model_fits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    # Circular FK pairs (studies<->extracted_rows, model_runs<->model_fits) are declared
    # use_alter=True, so SQLAlchemy omits them from CREATE TABLE. Add them here, once all
    # tables exist.
    op.create_foreign_key('fk_studies_legacy_row_id', 'studies', 'extracted_rows',
                          ['legacy_row_id'], ['id'])
    op.create_foreign_key('fk_model_runs_selected_model_id', 'model_runs', 'model_fits',
                          ['selected_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_model_runs_selected_model_id', 'model_runs', type_='foreignkey')
    op.drop_constraint('fk_studies_legacy_row_id', 'studies', type_='foreignkey')
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_imputation_proposals_id'), table_name='imputation_proposals')
    op.drop_table('imputation_proposals')
    op.drop_index(op.f('ix_model_fits_id'), table_name='model_fits')
    op.drop_table('model_fits')
    op.drop_table('trajectory_observations')
    op.drop_index(op.f('ix_model_runs_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_trajectory_definitions_id'), table_name='trajectory_definitions')
    op.drop_index(op.f('ix_trajectory_definitions_grouping_signature'), table_name='trajectory_definitions')
    op.drop_table('trajectory_definitions')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_index('ix_obs_type', table_name='observations')
    op.drop_index('ix_obs_arm_time', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_treatment_arms_id'), table_name='treatment_arms')
    op.drop_table('treatment_arms')
    op.drop_index(op.f('ix_lab_model_results_training_run_id'), table_name='lab_model_results')
    op.drop_index(op.f('ix_lab_model_results_project_id'), table_name='lab_model_results')
    op.drop_index(op.f('ix_lab_model_results_id'), table_name='lab_model_results')
    op.drop_table('lab_model_results')
    op.drop_table('ext_measurements')
    op.drop_table('ext_experiment_ingredients')
    op.drop_index(op.f('ix_experiment_microorganisms_id'), table_name='experiment_microorganisms')
    op.drop_table('experiment_microorganisms')
    op.drop_index(op.f('ix_asset_context_links_id'), table_name='asset_context_links')
    op.drop_index(op.f('ix_asset_context_links_asset_id'), table_name='asset_context_links')
    op.drop_table('asset_context_links')
    op.drop_index(op.f('ix_lab_training_runs_project_id'), table_name='lab_training_runs')
    op.drop_index(op.f('ix_lab_training_runs_job_id'), table_name='lab_training_runs')
    op.drop_index(op.f('ix_lab_training_runs_id'), table_name='lab_training_runs')
    op.drop_table('lab_training_runs')
    op.drop_index(op.f('ix_figure_conversion_cache_id'), table_name='figure_conversion_cache')
    op.drop_index(op.f('ix_figure_conversion_cache_docling_cache_id'), table_name='figure_conversion_cache')
    op.drop_table('figure_conversion_cache')
    op.drop_index(op.f('ix_extraction_runs_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_extraction_assets_project_id'), table_name='extraction_assets')
    op.drop_index(op.f('ix_extraction_assets_paper_id'), table_name='extraction_assets')
    op.drop_index(op.f('ix_extraction_assets_id'), table_name='extraction_assets')
    op.drop_table('extraction_assets')
    op.drop_index(op.f('ix_extracted_rows_id'), table_name='extracted_rows')
    op.drop_table('extracted_rows')
    op.drop_index(op.f('ix_ext_experiments_project_id'), table_name='ext_experiments')
    op.drop_index(op.f('ix_ext_experiments_paper_id'), table_name='ext_experiments')
    op.drop_index(op.f('ix_ext_experiments_id'), table_name='ext_experiments')
    op.drop_table('ext_experiments')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_condition_signature'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_study_project_doi', table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_doi_normalized'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_ext_evidence_paper_id'), table_name='ext_evidence')
    op.drop_index(op.f('ix_ext_evidence_id'), table_name='ext_evidence')
    op.drop_table('ext_evidence')
    op.drop_index(op.f('ix_export_runs_id'), table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_index(op.f('ix_docling_cache_paper_id'), table_name='docling_cache')
    op.drop_index(op.f('ix_docling_cache_id'), table_name='docling_cache')
    op.drop_index(op.f('ix_docling_cache_file_hash'), table_name='docling_cache')
    op.drop_table('docling_cache')
    op.drop_index(op.f('ix_uploaded_datasets_project_id'), table_name='uploaded_datasets')
    op.drop_index(op.f('ix_uploaded_datasets_id'), table_name='uploaded_datasets')
    op.drop_index(op.f('ix_uploaded_datasets_file_hash'), table_name='uploaded_datasets')
    op.drop_table('uploaded_datasets')
    op.drop_index(op.f('ix_threshold_definitions_id'), table_name='threshold_definitions')
    op.drop_table('threshold_definitions')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_file_hash'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_normalization_mappings_id'), table_name='normalization_mappings')
    op.drop_table('normalization_mappings')
    op.drop_index(op.f('ix_microorganisms_id'), table_name='microorganisms')
    op.drop_table('microorganisms')
    op.drop_index(op.f('ix_ext_ingredients_project_id'), table_name='ext_ingredients')
    op.drop_index(op.f('ix_ext_ingredients_id'), table_name='ext_ingredients')
    op.drop_table('ext_ingredients')
    op.drop_index(op.f('ix_ext_indicators_project_id'), table_name='ext_indicators')
    op.drop_index(op.f('ix_ext_indicators_id'), table_name='ext_indicators')
    op.drop_table('ext_indicators')
    op.drop_index(op.f('ix_dataset_snapshots_id'), table_name='dataset_snapshots')
    op.drop_table('dataset_snapshots')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
